name: Cross Crypto Compatibility Tests

on:
  push:
    paths:
      - '**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run tests
        run: |
          python -m unittest discover -s tests
